server:
  port: 0

spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:mariadb://localhost:3306/catalog?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: qwer1234
  sql:
    init:
      mode: always
  #초기 데이터가 테이블에 들어가도록 설정
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
    #스키마가 만들어지고 sql파일이 동작하게끔해줌
    defer-datasource-initialization: true

      

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com.amp.catalogsservice: DEBUG