
server:
  port: 0

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mariadb://localhost:3306/order?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: qwer1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true #show sql
        format_sql: true #To beautify or pretty print the SQL

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com.amp.orderservice: DEBUG