server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    dynamic: true
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: git
  cloud:
    config:
      server:
        native:
          search-locations: file://C:/${user.home}/Desktop/develop/native-file-repo
        git:
#          uri: file://C:\Users\user\Desktop\develop\git-local-repo
          uri: https://github.com/jjwoou9/git-local-repo.git
#          username:
#          password:

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh, bus-env, bus-refresh
